[[plugins]]
    repo = 'Shougo/dein.vim'


[[plugins]]
    repo = 'Shougo/vimproc.vim'
    build = 'make'


[[plugins]]
    repo = 'vim-airline/vim-airline'
    depends = ['vim-airline-themes']
    hook_add = '''
        let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
        let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
        set termguicolors

        let g:airline_powerline_fonts = 1
        let g:airline_theme = 'zenburn'
        let g:airline#extensions#tabline#enabled = 1
        nmap <C-j> <Plug>AirlineSelectNextTab
        nmap <C-k> <Plug>AirlineSelectPrevTab
        let g:airline_section_z = airline#section#create(['windowswap', '%3p%% ', 'linenr', ':%3v'])

        " Powerline系フォントを利用する
        let g:airline_powerline_fonts = 1
        if !exists('g:airline_symbols')
          let g:airline_symbols = {}
        endif

        " unicode symbols
        let g:airline_left_sep = '»'
        let g:airline_left_sep = '▶'
        let g:airline_right_sep = '«'
        let g:airline_right_sep = '◀'
        let g:airline_symbols.crypt = '🔒'
        let g:airline_symbols.linenr = '☰'
        let g:airline_symbols.linenr = '␊'
        let g:airline_symbols.linenr = '␤'
        let g:airline_symbols.linenr = '¶'
        let g:airline_symbols.maxlinenr = ''
        let g:airline_symbols.maxlinenr = '㏑'
        let g:airline_symbols.branch = '⎇'
        let g:airline_symbols.paste = 'ρ'
        let g:airline_symbols.paste = 'Þ'
        let g:airline_symbols.paste = '∥'
        let g:airline_symbols.spell = 'Ꞩ'
        let g:airline_symbols.notexists = '∄'
        let g:airline_symbols.whitespace = 'Ξ'

        " powerline symbols
        let g:airline_left_sep = ''
        let g:airline_left_alt_sep = ''
        let g:airline_right_sep = ''
        let g:airline_right_alt_sep = ''
        let g:airline_symbols.branch = ''
        let g:airline_symbols.readonly = ''
        let g:airline_symbols.linenr = '☰'
        let g:airline_symbols.maxlinenr = ''

        " airline-coc
        let g:airline#extensions#coc#enabled = 1
        let airline#extensions#coc#stl_format_err = '%E{[%e(#%fe)]}'
        let airline#extensions#coc#stl_format_warn = '%W{[%w(#%fw)]}'
    '''


[[plugins]]
    repo = 'vim-airline/vim-airline-themes'


[[plugins]]
    repo = 'Shougo/denite.nvim'
    hook_add = '''
        autocmd FileType denite call s:denite_my_settings()
        function! s:denite_my_settings() abort
          nnoremap <silent><buffer><expr> <CR>
          \ denite#do_map('do_action')
          nnoremap <silent><buffer><expr> <esc>
          \ denite#do_map('quit')
          nnoremap <silent><buffer><expr> i
          \ denite#do_map('open_filter_buffer')
          nnoremap <silent><buffer><expr> <BS>
          \ denite#do_map('move_up_path')
          nnoremap <silent><buffer><expr> d
          \ denite#do_map('do_action', 'delete')
          nnoremap <silent><buffer><expr> p
          \ denite#do_map('do_action', 'preview')
        endfunction

        autocmd FileType denite-filter call s:denite_filter_my_setting()
        function! s:denite_filter_my_setting() abort
            nnoremap <silent><buffer><expr> <esc>   denite#do_map('quit')
            inoremap <silent><buffer><expr> <esc>   denite#do_map('quit')
            nnoremap <silent><buffer><expr> <BS>    denite#do_map('nop')
        endfunction

        nnoremap [denite] <Nop>
        nmap <Space>j [denite]
        nnoremap <silent> J :<C-u>Denite -resume -immediately -cursor-pos=+1<CR>
        nnoremap <silent> K :<C-u>Denite -resume -immediately -cursor-pos=-1<CR>
        nnoremap <silent> [denite]j :<C-u>Denite -resume -filter-updatetime=1<CR>
        nnoremap <silent> [denite]k :<C-u>Denite buffer -filter-updatetime=1 -start-filter<CR>
        nnoremap <silent> [denite]l :<C-u>Denite line -filter-updatetime=1 -start-filter<CR>
        nnoremap <silent> [denite]' :<C-u>Denite grep -filter-updatetime=1 -start-filter<CR>
        nnoremap <silent> [denite]i :<C-u>Denite file/rec -filter-updatetime=1 -start-filter<CR>
        nnoremap <silent> [denite]o :<C-u>Denite file file:new -filter-updatetime=1 -start-filter<CR>
        nnoremap <silent> [denite]; :<C-u>Denite register -filter-updatetime=1<CR>
        nnoremap <silent> [denite]h :<C-u>Denite help -filter-updatetime=1 -start-filter<CR>

        call denite#custom#option('default', 'prompt', '>')

        let s:denite_win_width_percent = 0.85
        let s:denite_win_height_percent = 0.7

        " Change denite default options
        call denite#custom#option('default', {
            \ 'split': 'floating',
            \ 'winwidth': float2nr(&columns * s:denite_win_width_percent),
            \ 'wincol': float2nr((&columns - (&columns * s:denite_win_width_percent)) / 2),
            \ 'winheight': float2nr(&lines * s:denite_win_height_percent),
            \ 'winrow': float2nr((&lines - (&lines * s:denite_win_height_percent)) / 2),
            \ })

        augroup transparent-windows
          autocmd!
          autocmd FileType denite set winblend=10
          autocmd FileType denite-filter set winblend=10
        augroup END
    '''

[[plugins]]
    repo = 'tpope/vim-fugitive'
    hook_add = '''
        nnoremap <silent><C-s> :vertical bo Gstatus<CR>
        nnoremap <silent><C-x> :vertical bo Gdiff<CR>
    '''


[[plugins]]
    repo = 'airblade/vim-gitgutter'
    hook_add = '''
        set updatetime=500
        let g:gitgutter_map_keys = 0
        nmap <Down> <Plug>(GitGutterNextHunk)
        nmap <Up> <Plug>(GitGutterPrevHunk)
        nmap <Left> <Plug>(GitGutterPreviewHunk)
        nmap <Right> <Plug>(GitGutterStageHunk)
        nmap <C-u> <Plug>(GitGutterUndoHunk)
        omap ic <Plug>(GitGutterTextObjectInnerPending)
        omap ac <Plug>(GitGutterTextObjectOuterPending)
        xmap ic <Plug>(GitGutterTextObjectInnerVisual)
        xmap ac <Plug>(GitGutterTextObjectOuterVisual)
    '''

[[plugins]]
    repo = 'Shougo/defx.nvim'
    hook_add = '''
        nnoremap <silent> + 
        \ :Defx
        \ -columns=icons:indent:filename:type 
        \ -sort=extension
        \ -toggle
        \ -split=vertical
        \ -direction=botright
        \ -winwidth=60
        \ <CR>


        autocmd FileType defx call s:defx_my_settings()
        function! s:defx_my_settings() abort
            " Define mappings
            nnoremap <silent><buffer><expr> j
            \ line('.') == line('$') ? 'gg' : 'j'
            nnoremap <silent><buffer><expr> k
            \ line('.') == 1 ? 'G' : 'k'
            nnoremap <silent><buffer><expr> l
            \ defx#do_action('drop')
            nnoremap <silent><buffer><expr> h
            \ defx#do_action('cd', ['..'])
            nnoremap <silent><buffer><expr> J
            \ defx#do_action('open_tree')
            nnoremap <silent><buffer><expr> K
            \ defx#do_action('close_tree')
            nnoremap <silent><buffer><expr> L
            \ defx#do_action('open_tree_recursive')
            nnoremap <silent><buffer><expr> i
            \ defx#do_action('toggle_select')
            nnoremap <silent><buffer><expr> o
            \ defx#do_action('new_file')
            nnoremap <silent><buffer><expr> O
            \ defx#do_action('new_directory')
            nnoremap <silent><buffer><expr> ;
            \ defx#do_action('change_vim_cwd')
            nnoremap <silent><buffer><expr> u
            \ defx#do_action('cd', $PWD)
            nnoremap <silent><buffer><expr> *
            \ defx#do_action('toggle_select_all')
            nnoremap <silent><buffer><expr> .
            \ defx#do_action('toggle_ignored_files')
            nnoremap <silent><buffer><expr> C
            \ defx#do_action('copy')
            nnoremap <silent><buffer><expr> X
            \ defx#do_action('move')
            nnoremap <silent><buffer><expr> V
            \ defx#do_action('paste')
            nnoremap <silent><buffer><expr> D
            \ defx#do_action('remove')
            nnoremap <silent><buffer><expr> R
            \ defx#do_action('rename')
            nnoremap <silent><buffer><expr> Z
            \ defx#do_action('execute_system')
            nnoremap <silent><buffer><expr> Y
            \ defx#do_action('yank_path')
        endfunction
    '''


[[plugins]]
    repo = 'kristijanhusak/defx-icons'


[[plugins]]
    repo = 'cohama/lexima.vim'
    hook_add = '''
        call lexima#add_rule({'char': '$', 'input_after': '$', 'filetype': ['tex', 'markdown']})
        call lexima#add_rule({'char': '$', 'at': '\%#\$', 'leave': 1, 'filetype': ['tex', 'markdown']})
        call lexima#add_rule({'char': '<BS>', 'at': '\$\%#\$', 'delete': 1, 'filetype': ['tex', 'markdown']})
        call lexima#add_rule({'char': '<CR>', 'at': '\$\$\%#', 'input_after': '<CR>$$', 'filetype': ['markdown'] })
        call lexima#add_rule({'char': '<BS>', 'at': '\$\$\n\%#\n\$\$', 'delete': 3, 'filetype': ['markdown']})

        call lexima#add_rule({'char': '(', 'at': '\\left\%#', 'input_after': ' \right)', 'filetype': ['tex', 'markdown']})
        call lexima#add_rule({'char': '<BS>', 'at': '\\left(\%#',
        \ 'input': '<BS><BS><BS><BS><BS><BS><Del><Del><Del><Del><Del><Del><Del><Del>', 'filetype': ['tex', 'markdown']})
        call lexima#add_rule({'char': '[', 'at': '\\left\%#', 'input_after': ' \right]', 'filetype': ['tex', 'markdown']})
        call lexima#add_rule({'char': '<BS>', 'at': '\\left[\%#',
        \ 'input': '<BS><BS><BS><BS><BS><BS><Del><Del><Del><Del><Del><Del><Del><Del>', 'filetype': ['tex', 'markdown']})
        call lexima#add_rule({'char': '{', 'at': '\\left\\\%#', 'input_after': ' \right\}', 'filetype': ['tex', 'markdown']})
        call lexima#add_rule({'char': '<BS>', 'at': '\\left\\{\%#',
        \ 'input': '<BS><BS><BS><BS><BS><BS><BS><Del><Del><Del><Del><Del><Del><Del><Del><Del>', 'filetype': ['tex', 'markdown']})
        call lexima#add_rule({'char': '{', 'at': '\\\%#', 'input_after': ' \}', 'filetype' : ['tex', 'markdown']})
        call lexima#add_rule({'char': '<BS>', 'at': '\\{\%#', 'input': '<BS><BS><Del><Del><Del>', 'filetype' : ['tex', 'markdown']})

        inoremap <silent><C-l> <C-r>=lexima#insmode#leave(1, '<LT>C-G>U<LT>RIGHT>')<CR>
        inoremap <silent><C-h> <C-r>=lexima#insmode#leave_all('<LT>C-G>U<LT>LEFT>')<CR>
    '''


[[plugins]]
    repo = 'rhysd/clever-f.vim'
    hook_add = '''
        let g:clever_f_not_overwrites_standard_mappings = 1
        map <expr> f expand("<cword>")!~"^$" ? "<Plug>(clever-f-f)" : ""
        map <expr> F expand("<cword>")!~"^$" ? "<Plug>(clever-f-F)" : ""
        nmap <space>f <Plug>(clever-f-reset)
        let g:clever_f_smart_case = 1
        let g:clever_f_mark_direct = 1
        let g:clever_f_chars_match_any_signs = ";"
    '''


[[plugins]]
    repo = 'easymotion/vim-easymotion'
    hook_add = '''
        let g:EasyMotion_do_mapping = 0
        map ; <Plug>(easymotion-bd-jk)
        nmap ; <Plug>(easymotion-overwin-line)
    '''


[[plugins]]
    repo = 'tpope/vim-commentary'


[[plugins]]
    repo = 'tpope/vim-surround'
    hook_add = '''
        nmap S ysiW
        nmap SS ysiw<space><space>
    '''


[[plugins]]
    repo = 'tpope/vim-repeat'


[[plugins]]
    repo = 'vim-jp/vimdoc-ja'


[[plugins]]
    repo = 'nathanaelkane/vim-indent-guides'
    hook_add = '''
        nnoremap <silent>\| :IndentGuidesToggle<CR>
        let g:indent_guides_guide_size = 1
        let g:indent_guides_exclude_filetypes = ['help']
        let g:indent_guides_auto_colors = 0
        autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd   ctermbg=214 guibg=#c1c95c
        autocmd VimEnter,Colorscheme * :hi IndentGuidesEven  ctermbg=75 guibg=#51a2c5
    '''
